### ISSUE TITLE
Recommendation: Add README.MD file in each sample

### ISSUE THREAD

**Issue by BastiaanOlij** [GodotVR/godot_openxr_vendors#179]
Have a look at how this is applied in https://github.com/godotengine/godot-demo-projects, each project has its own readme which means that we see the contents of this readme when we check out a sample in Github.

It would be great to have a short description and some screenshots with each sample, especially when this list grows.

**Comment by devloglogan** [comment]
Agreed! I'll definitely add this soon. :)
