### ISSUE TITLE
Could I have a chance to re-adapt the openXR interface based on this project?

### ISSUE THREAD

**Issue by toby018** [GodotVR/godot_openxr_vendors#204]
We have changed some of the implementation of the openXR interface, which requires the plugin to re-adapt these interfaces, but I can't find code like ARVRInterface.cpp and OpenXRApi.cpp in this project, these can be found in the godot_openxr project, can I have a chance to re-adapt the openXR interface based on this project?

**Comment by dsnopek** [comment]
>  I can't find code like ARVRInterface.cpp and OpenXRApi.cpp in this project

Support for OpenXR is built in to Godot 4.x itself - this repo is just for vendor extensions to OpenXR.

If you're still using Godot 3.x (which perhaps you are given the reference to `ARVRInterface` - in Godot 4.x, this is `XRInterface`), then you'll need to continue using [godot_openxr](https://github.com/godotvr/godot_openxr).

**Comment by dsnopek** [comment]
Without more information, I'm not sure what the next steps are for this one. So, I'm going to close it, but if you can provide more information on what you're trying to accomplish, we can re-open it
