### ISSUE TITLE
Formatting checks report errors in CI

### ISSUE THREAD

**Issue by Malcolmnixon** [GodotVR/godot_openxr_vendors#212]
The Static Checks action for checking format is generating a stream of clang-format parse errors:
```
YAML:15:18: error: invalid boolean
AlignOperands:   DontAlign
                 ^~~~~~~~~
Error reading /home/runner/work/godot_openxr_vendors/godot_openxr_vendors/.clang-format: Invalid argument
YAML:1[5](https://github.com/Malcolmnixon/godot_openxr_vendors/actions/runs/11118011256/job/30890912770#step:5:6):18: error: invalid boolean
AlignOperands:   DontAlign
                 ^~~~~~~~~
Error reading /home/runner/work/godot_openxr_vendors/godot_openxr_vendors/.clang-format: Invalid argument
YAML:15:1[8](https://github.com/Malcolmnixon/godot_openxr_vendors/actions/runs/11118011256/job/30890912770#step:5:9): error: invalid boolean
AlignOperands:   DontAlign
                 ^~~~~~~~~
```

The reason appears to be the .clang-format `AlignOperands:   DontAlign` which I believe should be `AlignOperands:   false`

**Comment by Malcolmnixon** [comment]
@devloglogan Could you look into this as I believe you checked in the initial clang-format file with this option.

**Comment by Malcolmnixon** [comment]
Found it - the clang-format file is virtually identical to the godot main repo (so we can follow a similar coding convention) however the godot static-checks job runs on Ubuntu 22.04 and we're running on Ubuntu 20.04. These releases of Ubuntu have wildly different versions of clang-format and the configuration files are incompatible.

We need to update the static-checks job to 22.04 and then fix coding violations that have crept in.

**Comment by devloglogan** [comment]
Fixed by https://github.com/GodotVR/godot_openxr_vendors/pull/214!
