### ISSUE TITLE
Nothing renders in passthrough apart from passthrough itself (Quest3)

### ISSUE THREAD

**Issue by TheBricktop** [GodotVR/godot_openxr_vendors#217]
Just like in title after setting up the scene with some default boxes around to test and global mesh as in godotxr documentation,
but after export to quest the only thing I can see is passthrough vision but none of the virtual 3d objects. I cant figure what this time is wrong with it.

**Comment by dsnopek** [comment]
When you have passthrough disabled, do you see the virtual objects?

Could you share a minimum reproduction project (MRP)? In my test projects, including the "meta-passthrough-sample" included in this repo, the passthrough and virtual objects work with Godot 4.3, so I suspect it's something in your project. I'd also be curious how that sample works for you?

**Comment by dsnopek** [comment]
Given that this is working for most folks, and we haven't gotten any further feedback, I'm going to close this for now. We can always re-open it if we get more information
