### ISSUE TITLE
Metalic materials don't reflect the skybox

### ISSUE THREAD

**Issue by goatchurchprime** [GodotVR/godot_openxr_vendors#59]
Here's a section from the Quest2 where I have a panorama sky set from an image with metalic=0.96 roughness=0 (running mobile renderer).

![image](https://github.com/GodotVR/godot_openxr_vendors/assets/677254/400976df-6da1-49d8-a341-f745956a07ca)

This is the same exact code running as deployed on my Android phone
![image](https://github.com/GodotVR/godot_openxr_vendors/assets/677254/4885f175-43ea-46b7-ba64-68f1cf0d9bc6)

So it must be a mobile-VR problem, not a mobile Android problem

(Same problem of no skybox reflection on the Pico4 as well.)

**Comment by BastiaanOlij** [comment]
This is (was?) an issue in Godot itself, I think it has been fixed.

**Comment by dsnopek** [comment]
If this is still an issue, it's a Godot issue, and should be opened there (if there isn't already an issue tracking it).
