### ISSUE TITLE
There is no option to enable the plugin

### ISSUE THREAD

**Issue by AdversaryAvery** [GodotVR/godot_openxr_vendors#69]
I am missing the option to enable the plugin, so the Action Map is unable to open

**Comment by BastiaanOlij** [comment]
The action map is enabled by enabling OpenXR in the project settings.

This plugin missing the enable settings likely means it was installed in the wrong place.

**Comment by AdversaryAvery** [comment]
Thank you. I will reinstall and try again

**Comment by AdversaryAvery** [comment]
This seems to have solved the issue

**Comment by x3haloed** [comment]
> This seems to have solved the issue

Any help? I'm on macOS. I've installed once from the AssetLibrary and once by hand. Still no option to enable the plugin.

**Comment by x3haloed** [comment]
Update ... I noted that you migrated over to C++ for 2.0.3. I installed 2.0.2 instead and it works. I'm guessing that the binary for macOS aarch64 is missing or there's some other problem with the C++ binaries.

**Comment by m4gr3d** [comment]
@x3haloed you should not need to enable the plugin for version 2.0.3 and higher as it's automatically enabled. 
Take a look in the export settings and you should see the options exposed by the plugin
