### ISSUE TITLE
PICO 4 Hand tracking and Passthrough

### ISSUE THREAD

**Issue by LakoMoor** [GodotVR/godot_openxr_vendors#90]
Hi. How to get passthrough and hand tracking working on pico 4?  I only see meta support in the settings
![image](https://github.com/GodotVR/godot_openxr_vendors/assets/44299427/91793065-074b-43c3-bfea-c321a3a2dcd2)

**Comment by herbertsschaefe** [comment]
Hey! It will work on the Pico 4 just the same. 

I am not sure if you also have to set the options on the Meta XR Features for a Pico build, but as long as your project is properly configured for OpenXR with handtracking enabled, and your Pico 4 have handtracking also enabled then it will work the same as the Meta Quest. Same with passthrought.

**Comment by m4gr3d** [comment]
@BastiaanOlij Are there manifest tags / permissions that need to be added for Pico devices?

**Comment by BastiaanOlij** [comment]
@m4gr3d I don't believe so, if I recall correctly only extra manifest entries were needed for eye tracking. Though it was Dirk who did any changes needed to make Pico work way back when so it may be good to compare the old loaders plugin to see if we lost any in the refactor.

Do note that for pass through, @dsnopek changes were merged in master last week, while the changes in the vendor plugin are still being finalised, and passthrough will definitely not work on master with the 2.0.3 release.

**Comment by m4gr3d** [comment]
Sounds good! Closing the issue then.

@LakoMoor Feel free to reopen if you run into issues getting it to work.
